// svelte-benchmark/src/pages/PostsPage.svelte
<script>
    import Post from '../components/Post.svelte';
	import { getPosts } from '../shared/api';
    import { SORT_OPTIONS } from '../shared/helpers/sortOptions';
    import SearchIcon from '../shared/icons/search.svg';
    import '../shared/styles/search.css';

    let posts = getPosts();
    let searchValue = "";
    let selectedSortOption = SORT_OPTIONS[0].value;

    const handleFetchPosts = () => getPosts({ sortOption: selectedSortOption,searchTerm: searchValue.trim()});

    const handleSubmit = () => {
        posts = handleFetchPosts();
    }
</script>

<div class="posts-search-bar-container">
    <form class="search-input-container" on:submit|preventDefault={handleSubmit}>
        <input type="text" placeholder="Search for post" class="search-input" bind:value={searchValue} />
        <button type="submit" class="search-input__button">
            <img
            src={SearchIcon}
            alt="search icon"
            height="14"
            width="14"
            />
        </button>
    </form>
    <!-- svelte-ignore a11y-no-onchange -->
    <select bind:value={selectedSortOption} class="post-sort__select" on:change={handleSubmit}>
        {#each SORT_OPTIONS as sortOption}
            <option value={sortOption.value} >{ sortOption.label }</option>
        {/each} 
    </select>
</div>
{#each posts as post}
	<Post {post} />
{/each}

// angular-benchmark/src/app/postsPage/postsPage.component.ts
import { Component } from '@angular/core';
import { getPosts } from 'src/shared/api';
// @ts-ignore
import SearchIcon from 'src/shared/icons/search.svg';
// @ts-ignore
import { SORT_OPTIONS, SORT_FILTERS } from 'src/shared/helpers/sortOptions';

@Component({
  selector: 'postPage',
  templateUrl: './postsPage.component.html',
  styleUrls: ['../../shared/styles/posts.css', '../../shared/styles/search.css'],
})
export class PostsPageComponent {
  searchTerm = '';
  chosenSortOption = SORT_FILTERS.NONE;
  searchIcon = SearchIcon;
  posts = getPosts();

  get sortOptions() {
    return SORT_OPTIONS;
  }

  onSubmit() {
    this.posts = getPosts({
      searchTerm: this.searchTerm,
      sortOption: this.chosenSortOption,
    });
  }
}
