// angular-benchmark/src/app/post/post.component.ts
import { Component, Input } from '@angular/core';
import { Post } from 'src/shared/api';
import { shortenPostContent } from 'src/shared/helpers/formatters';

@Component({
  selector: 'post',
  templateUrl: './post.component.html',
  styleUrls: ['../../shared/styles/posts.css'],
})
export class PostComponent {
  @Input() post!: Post;
  @Input() isOpen: boolean = false;

  get postContent() {
    return this.isOpen
      ? this.post.content
      : shortenPostContent(this.post.content);
  }
}

<div class="post-container">
  <div class="post__header">
    <img
      [src]="post.user.avatar"
      [alt]="'avatar of ' + post.user.name"
      class="post__avatar"
      width="50"
      height="50"
    />
    <div>
      <p class="post__author">{{ post.user.name }}</p>
      <p class="post__date">{{ post.createdAt }}</p>
    </div>
  </div>
  <p>{{ postContent }}</p>
  <a *ngIf="!isOpen" class='post__read-more' [routerLink]="['/posts', post.id]">
    Czytaj więcej...
  </a>

</div>

// svelte-benchmark/src/components/Post.svelte
<script>
    import { Link } from 'svelte-routing';
    import { shortenPostContent } from '../shared/helpers/formatters';
	import '../shared/styles/posts.css';

    export let post;
    export let isOpen = false;
</script>

<div class='post-container'>
    <div class='post__header'>
      <img
        src={post.user.avatar}
        alt={`avatar of ${post.user.name}`}
        class='post__avatar'
        width={50}
        height={50}
      />
      <div>
        <p class='post__author'>{post.user.name}</p>
        <p class='post__date'>{post.createdAt}</p>
      </div>
    </div>
    
    {#if !isOpen}
      <p>{shortenPostContent(post.content)}</p>
      <Link class='post__read-more' to={`posts/${post.id}`}>
        Czytaj więcej...
      </Link>
    {:else}
      <p>{post.content}</p>
    {/if}
  </div>
