// react-benchmark/src/App.js
import { useState } from 'react';
import { getPosts } from './shared/api';
import Post from './components/Post';
import PostPage from './components/PostPage';
import { Switch, Route } from 'react-router-dom';
import './App.css';
import './shared/styles/posts.css';

function App() {
  const [posts, ] = useState(getPosts);
  return (
    <Switch>
      <Route path='/posts/:id' component={PostPage} />
      <Route path='/'>
        <div className='App'>
          {posts.map((post) => (
            <Post key={post.id} post={post} />
          ))}
        </div>
      </Route>
    </Switch>
  );
}

export default App;

// angular-benchmark/src/app/app.component.ts
import { Component } from '@angular/core';
import { getPosts } from 'src/shared/api';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['../shared/styles/posts.css']
})
export class AppComponent {
  posts = getPosts();
}

<post *ngFor="let post of posts" [post]="post">
</post>
