// react-benchmark/src/App.js
import { Switch } from 'react-router-dom';
import PostPage from './pages/Post';
import PostsPage from './pages/Posts';
import RouteWithLayout from './components/RouteWithLayout';
import './App.css';
import './shared/styles/posts.css';

function App() {
  return (
    <Switch>
      <RouteWithLayout path='/posts/:id' component={PostPage} />
      <RouteWithLayout path='/' component={PostsPage} />
    </Switch>
  );
}

export default App;

// svelte-benchmark/src/App.svelte
<script>
	import { Router } from "svelte-routing";
	import PostPage from './pages/PostPage.svelte';
	import PostsPage from './pages/PostsPage.svelte';
	import Route from './components/Route.svelte';
</script>

<Router>
	<Route path="/posts/:id" let:params>
		<PostPage postId="{params.id}" />
	</Route>
	<Route path="/" component={PostsPage} />
</Router>
